options {
    //Hier können noch Optionen stehen z.B. static
    STATIC = false;
}

PARSER_BEGIN(PostFixExprParse) //Hier muss der Klassenname stehen
package parser;

import JavaClassFileGenerator.CodeGen;
import JavaClassFileGenerator.JavaClassFileGenerator;
import JavaClassFileGenerator.MethodObject;
import symbolTable.SymbolTable;

public class PostFixExprParse {
    private final SymbolTable st = new SymbolTable();
    private final CodeGen code = new CodeGen(st);

    public static void main (String[] args) {
        PostFixExprParse parser = new PostFixExprParse(System.in);
        try {
            parser.program(); //Aufruf mit Startsymbol
            String mainHex = parser.code.finishMain();
            JavaClassFileGenerator jcfg = new JavaClassFileGenerator("generated/Main", true, true, true);
            MethodObject mainMethod = new MethodObject("main", 1, mainHex);
            jcfg.generateClassFile(mainMethod);
        } catch (ParseException e) {
            System.err.println(e);
        }
    }
}
PARSER_END(PostFixExprParse)

SKIP: {
      " " //Blank
      | "\r" //Wagenrücklauf (return)
      | "\n" //Neue Zeile (new line)
      | "\t" //Tabulator
}

TOKEN: {
    < INT : "int" > //Schlüsselwort
    | < FINAL : "final" > //& später "int" einsetzen
    | < PRINT : "print" > // VOR IDENT!
    | < IF : "if" > // VOR IDENT!
    | < ELSE : "else" > // VOR IDENT!
    | < WHILE : "while" > // VOR IDENT!
    | < IDENT : ["a"-"z"] (["a"-"z","A"-"Z","0"-"9"])* >
    | < NUMBER : "0" | (["1"-"9"] (["0"-"9"])*) >
    | < PLUS   : "+" >
    | < MINUS  : "-" >
    | < MULT   : "*" >
    | < DIV    : "/" >
    | < KLAMMERAUF : "(" >
    | < KLAMMERZU : ")" >
    | < CURLYAUF : "{" >
    | < CURLYZU : "}" >
    | < EQUAL : "=" >
    | < COMMA : "," >
    | < SEMICOLON : ";" >
    | < COMPOP : "=" | ">" | ">=" | "<" | "<=" >
}

void program(): {} {
    constDecl()
    varDecl()
    statement()
}

void constDecl(): {} {
    ( <FINAL> <INT> constZuw() constList() <SEMICOLON> )?
}

void constZuw(): { Token ident; Token number; } {
  ident=<IDENT> <EQUAL> number=<NUMBER>
  { st.addConstant(ident.image, Integer.parseInt(number.image)); }
}

void constList(): {} {
    ( <COMMA> constZuw() constList() )?
}

void varDecl(): { Token ident; } {
    ( <INT> ident=<IDENT> { st.addVariable(ident.image); } varZuw(ident) varList() <SEMICOLON> )?
}

void varZuw(Token id): { Token number; } {
    ( <EQUAL> number=<NUMBER> { code.initVar(id.image, Integer.parseInt(number.image)); } )?
}

void varList(): { Token id; } {
    ( <COMMA> id=<IDENT> { st.addVariable(id.image); } varZuw(id) varList() )?
}

void expression(): {} {
    term() summe()
}

void summe(): {} {
    ( <PLUS>  term() { code.add(); } summe()
    | <MINUS> term() { code.sub(); } summe()
    )?
}

void term(): {} {
    faktor() product()
}

void product(): {} {
    ( <MULT> faktor() { code.mul(); } product()
    | <DIV>  faktor() { code.div(); } product()
    )?
}

void faktor(): { Token n; Token id; } {
    n=<NUMBER> { code.pushInt(Integer.parseInt(n.image)); }
  | id=<IDENT> { code.load(id.image); }
  | <KLAMMERAUF> expression() <KLAMMERZU>
}

void statement(): {} { // nur print erlaubt
    <PRINT> <KLAMMERAUF> expression() <KLAMMERZU> <SEMICOLON>
    { code.print(); }
}
