/* PostFixExprParse.java */
/* Generated By:JavaCC: Do not edit this line. PostFixExprParse.java */
                               //Hier muss der Klassenname stehen
package parser;

import JavaClassFileGenerator.CodeGen;
import JavaClassFileGenerator.JavaClassFileGenerator;
import JavaClassFileGenerator.MethodObject;
import symbolTable.SymbolTable;
import parser.exceptions.LWertException;

public class PostFixExprParse implements PostFixExprParseConstants {
    private final SymbolTable st = new SymbolTable();
    private final CodeGen code = new CodeGen(st);

    public static void main (String[] args) {
        PostFixExprParse parser = new PostFixExprParse(System.in);
        try {
            parser.program(); //Aufruf mit Startsymbol
            String mainHex = parser.code.finishMain();
            JavaClassFileGenerator jcfg = new JavaClassFileGenerator("generated/Main", true, true, true);
            MethodObject mainMethod = new MethodObject("main", 1, mainHex);
            jcfg.generateClassFile(mainMethod);
        } catch (ParseException e) {
            System.err.println(e);
        }
    }

  final public void program() throws ParseException, LWertException {
    constDecl();
    varDecl();
    statement();
    jj_consume_token(0);
}

  final public void constDecl() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case FINAL:{
      jj_consume_token(FINAL);
      jj_consume_token(INT);
      constZuw();
      constList();
      jj_consume_token(SEMICOLON);
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
}

  final public void constZuw() throws ParseException {Token ident; Token number;
    ident = jj_consume_token(IDENT);
    jj_consume_token(EQUAL);
    number = jj_consume_token(NUMBER);
st.addConstant(ident.image, Integer.parseInt(number.image));
}

  final public void constList() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMMA:{
      jj_consume_token(COMMA);
      constZuw();
      constList();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
}

  final public void varDecl() throws ParseException {Token ident;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      jj_consume_token(INT);
      ident = jj_consume_token(IDENT);
st.addVariable(ident.image);
      varZuw(ident);
      varList();
      jj_consume_token(SEMICOLON);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
}

  final public void varZuw(Token ident) throws ParseException {Token number;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQUAL:{
      jj_consume_token(EQUAL);
      number = jj_consume_token(NUMBER);
code.initVar(ident.image, Integer.parseInt(number.image));
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
}

  final public void varList() throws ParseException {Token ident;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMMA:{
      jj_consume_token(COMMA);
      ident = jj_consume_token(IDENT);
st.addVariable(ident.image);
      varZuw(ident);
      varList();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
}

  final public void expression() throws ParseException {
    term();
    summe();
}

  final public void summe() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
        term();
code.add();
        summe();
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        term();
code.sub();
        summe();
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
}

  final public void term() throws ParseException {
    faktor();
    product();
}

  final public void product() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MULT:
    case DIV:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:{
        jj_consume_token(MULT);
        faktor();
code.mul();
        product();
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
        faktor();
code.div();
        product();
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
}

  final public void faktor() throws ParseException {Token n; Token ident;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMBER:{
      n = jj_consume_token(NUMBER);
code.push(Integer.parseInt(n.image));
      break;
      }
    case IDENT:{
      ident = jj_consume_token(IDENT);
code.load(ident.image);
      break;
      }
    case KLAMMERAUF:{
      jj_consume_token(KLAMMERAUF);
      expression();
      jj_consume_token(KLAMMERZU);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public int condition() throws ParseException {Token op; int jumpPlaceholder;
    expression();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQ:{
      op = jj_consume_token(EQ);
      break;
      }
    case NE:{
      op = jj_consume_token(NE);
      break;
      }
    case GE:{
      op = jj_consume_token(GE);
      break;
      }
    case GT:{
      op = jj_consume_token(GT);
      break;
      }
    case LE:{
      op = jj_consume_token(LE);
      break;
      }
    case LT:{
      op = jj_consume_token(LT);
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    expression();
switch (op.kind) {
      case EQ: jumpPlaceholder = code.if_icmpne(); break; // a==b  -> springe, wenn a!=b
      case NE: jumpPlaceholder = code.if_icmpeq(); break; // a!=b  -> springe, wenn a==b
      case LT: jumpPlaceholder = code.if_icmpge(); break; // a<b   -> springe, wenn a>=b
      case GE: jumpPlaceholder = code.if_icmplt(); break; // a>=b  -> springe, wenn a<b
      case GT: jumpPlaceholder = code.if_icmple(); break; // a>b   -> springe, wenn a<=b
      case LE: jumpPlaceholder = code.if_icmpgt(); break; // a<=b  -> springe, wenn a>b
      default: {if (true) throw new ParseException("TEST");}
    }
    { {if ("" != null) return jumpPlaceholder;} }
    throw new Error("Missing return statement in function");
}

  final public void statement() throws ParseException, LWertException {Token ident; int falseJump; int endJump; int loopStart;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENT:{
      ident = jj_consume_token(IDENT);
      jj_consume_token(EQUAL);
      expression();
      jj_consume_token(SEMICOLON);
if (!st.isVar(ident.image)) {
        {if (true) throw new LWertException("Zuweisung auf Konstante: " + ident.image);}
      }
      code.store(ident.image);
      break;
      }
    case PRINT:{
      jj_consume_token(PRINT);
      jj_consume_token(KLAMMERAUF);
      expression();
      jj_consume_token(KLAMMERZU);
      jj_consume_token(SEMICOLON);
code.print();
      break;
      }
    case CURLYAUF:{
      jj_consume_token(CURLYAUF);
      stmtLIST();
      jj_consume_token(CURLYZU);
      break;
      }
    case IF:{
      jj_consume_token(IF);
      falseJump = condition();
      statement();
      optElse(falseJump);
      break;
      }
    case WHILE:{
      jj_consume_token(WHILE);
loopStart = code.pc(); // Start der Schleife merken

      falseJump = condition();
      statement();
// Mit GOTO zurück zum Schleifenanfang (per Platzhalter + Patch)
      int back = code.ifFalse_goto();
      code.patchJumpPlaceholder(back, loopStart);

      // false-Zweig (Abbruch) auf hier patchen
      code.patchJumpPlaceholder(falseJump, code.pc());
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void optElse(int falseJump) throws ParseException, LWertException {boolean hasElse = false; int endJump = -1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
hasElse = true;
        // False der Bedingung landet am Anfang von else:
        endJump = code.ifFalse_goto();
        System.out.println(code.hex);
        code.patchJumpPlaceholder(falseJump, code.pc());
      statement();
// nach else-Block: (skip else wenn Bedingung true)
        System.out.println(code.hex);
        code.patchJumpPlaceholder(endJump, code.pc());
        System.out.println(code.hex);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
if (!hasElse) {
            // kein else: False-Zweig fällt hinter das THEN – hier patchen
            code.patchJumpPlaceholder(falseJump, code.pc());
        }
}

  final public void stmtLIST() throws ParseException, LWertException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PRINT:
    case IF:
    case WHILE:
    case IDENT:
    case CURLYAUF:{
      statement();
      stmtLIST();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
}

  /** Generated Token Manager. */
  public PostFixExprParseTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[14];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x40,0x400000,0x20,0x200000,0x400000,0x6000,0x6000,0x18000,0x18000,0x21800,0x3f000000,0x80d80,0x200,0x80d80,};
	}

  /** Constructor with InputStream. */
  public PostFixExprParse(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public PostFixExprParse(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new PostFixExprParseTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public PostFixExprParse(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new PostFixExprParseTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new PostFixExprParseTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public PostFixExprParse(PostFixExprParseTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(PostFixExprParseTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[30];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 14; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 30; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
