/* PostFixExprParse.java */
/* Generated By:JavaCC: Do not edit this line. PostFixExprParse.java */
package parser;

import JavaClassFileGenerator.BytecodeGenerator;
import JavaClassFileGenerator.JavaClassFileGenerator;
import JavaClassFileGenerator.MethodObject;
import symbolTable.Method;
import symbolTable.SymbolTable;
import parser.exceptions.LWertException;
import parser.exceptions.RWertException;
import parser.exceptions.WrongParametersException;
import parser.exceptions.UnknownSymbolException;
import parser.exceptions.SymbolAlreadyDefinedException;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PostFixExprParse implements PostFixExprParseConstants {
    private final SymbolTable symbolTable = new SymbolTable();
    // Methoden-Speicher
    private final Map<String, Method> methods = new HashMap<>();
    private Method currentMethod;

    public static void main (String[] args) {
        PostFixExprParse parser = new PostFixExprParse(System.in);
        try {
            parser.program();

            JavaClassFileGenerator jcfg = new JavaClassFileGenerator("generated/Main", true, true, true);
            List<MethodObject> methodObjects = new ArrayList<>();

            // Bytecode aller Methoden einsammeln
            for (Method m : parser.methods.values()) {
                String hexCode;
                if (m.getName().equals("main")) {
                    hexCode = m.getCode().finishMain();
                } else {
                    hexCode = m.getCode().finish();
                }

                System.out.println("Method " + m.getName() + " Hex: " + hexCode);
                methodObjects.add(new MethodObject(m.getName(), m.getParamCount(), hexCode));
            }

            jcfg.generateClassFile(methodObjects.toArray(new MethodObject[0]));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

  final public void program() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException {
// Main-Methode initialisieren
        currentMethod = new Method("main", false, symbolTable);
        currentMethod.addParameter("args");
        methods.put("main", currentMethod);
    constDecl();
    varDecl(false);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNC:
      case VOID:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VOID:{
        procedure();
        break;
        }
      case FUNC:{
        function();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
currentMethod = methods.get("main");
    statement();
    jj_consume_token(0);
}

  final public void constDecl() throws ParseException, SymbolAlreadyDefinedException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case FINAL:{
      jj_consume_token(FINAL);
      jj_consume_token(INT);
      constZuw();
      constList();
      jj_consume_token(SEMICOLON);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
}

  final public void constZuw() throws ParseException, SymbolAlreadyDefinedException {Token ident; Token number;
    ident = jj_consume_token(IDENT);
    jj_consume_token(EQUAL);
    number = jj_consume_token(NUMBER);
symbolTable.addConstant(ident.image, Integer.parseInt(number.image));
}

  final public void constList() throws ParseException, SymbolAlreadyDefinedException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMMA:{
      jj_consume_token(COMMA);
      constZuw();
      constList();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
}

  final public void varDecl(boolean isLocal) throws ParseException, SymbolAlreadyDefinedException {Token ident;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      jj_consume_token(INT);
      ident = jj_consume_token(IDENT);
if (isLocal) {
                currentMethod.addLocalVariable(ident.image);
            } else {
                symbolTable.addVariable(ident.image);
            }
      varZuw(ident, isLocal);
      varList(isLocal);
      jj_consume_token(SEMICOLON);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
}

  final public void varZuw(Token ident, boolean isLocal) throws ParseException {Token number;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQUAL:{
      jj_consume_token(EQUAL);
      number = jj_consume_token(NUMBER);
int val = Integer.parseInt(number.image);
            if (isLocal) {
                // Lokal: Wert auf Stack und speichern
                currentMethod.getCode().initLocalVar(currentMethod.getVarIndex(ident.image), val);
            } else {
                // Global: Init-Code in Main
                currentMethod.getCode().initVar(ident.image, val);
            }
      break;
      }
    default:
      jj_la1[5] = jj_gen;
// Default-Initialisierung mit 0
        if (isLocal) {
            currentMethod.getCode().initLocalVar(currentMethod.getVarIndex(ident.image), 0);
        } else {
            currentMethod.getCode().initVar(ident.image, 0);
        }
    }
}

  final public void varList(boolean isLocal) throws ParseException, SymbolAlreadyDefinedException {Token ident;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMMA:{
      jj_consume_token(COMMA);
      ident = jj_consume_token(IDENT);
if (isLocal) currentMethod.addLocalVariable(ident.image);
            else symbolTable.addVariable(ident.image);
      varZuw(ident, isLocal);
      varList(isLocal);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
}

  final public void expression() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {
    summe();
}

  final public void summe() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {
    product();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
        product();
currentMethod.getCode().add();
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        product();
currentMethod.getCode().sub();
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void product() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {
    term();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:
      case DIV:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:{
        jj_consume_token(MULT);
        term();
currentMethod.getCode().mul();
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
        term();
currentMethod.getCode().div();
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void term() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {Token n; Token ident;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMBER:{
      n = jj_consume_token(NUMBER);
currentMethod.getCode().push(Integer.parseInt(n.image));
      break;
      }
    case IDENT:{
      // Linksfaktorisierung: IDENT konsumieren, dann entscheiden
          ident = jj_consume_token(IDENT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case KLAMMERAUF:{
        functionCall(ident);
        break;
        }
      default:
        jj_la1[11] = jj_gen;
int localIndex = currentMethod.getVarIndex(ident.image);
            if (localIndex != -1) {
                currentMethod.getCode().loadLocal(localIndex);
            } else if (symbolTable.isConst(ident.image)) {
                currentMethod.getCode().push(symbolTable.constValue(ident.image));
            } else if (symbolTable.isVar(ident.image)) {
                currentMethod.getCode().loadGlobal(ident.image);
            } else {
                {if (true) throw new RWertException("Bezeichner unbekannt oder keine Variable/Konstante: " + ident.image);}
            }
      }
      break;
      }
    case KLAMMERAUF:{
      jj_consume_token(KLAMMERAUF);
      expression();
      jj_consume_token(KLAMMERZU);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void functionCall(Token ident) throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {int argsCount = 0;
    jj_consume_token(KLAMMERAUF);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case KLAMMERAUF:
    case IDENT:
    case NUMBER:{
      expression();
argsCount++;
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        expression();
argsCount++;
      }
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
    jj_consume_token(KLAMMERZU);
if (!methods.containsKey(ident.image)) {
             {if (true) throw new UnknownSymbolException();}
        } else {
             Method m = methods.get(ident.image);
             if (m.getParamCount() != argsCount) {
                 {if (true) throw new WrongParametersException("Funktion " + ident.image + " erwartet " + m.getParamCount() + " Parameter, aber " + argsCount + " gegeben.");}
             }
        }
        currentMethod.getCode().writeCall(ident.image, argsCount);
}

  final public void procCall(Token ident) throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {int argsCount = 0;
    jj_consume_token(KLAMMERAUF);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case KLAMMERAUF:
    case IDENT:
    case NUMBER:{
      expression();
argsCount++;
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMMA);
        expression();
argsCount++;
      }
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    jj_consume_token(KLAMMERZU);
if (!methods.containsKey(ident.image)) {
             {if (true) throw new UnknownSymbolException();}
        }

        Method m = methods.get(ident.image);
        if (m.getParamCount() != argsCount) {
             {if (true) throw new WrongParametersException("Prozedur " + ident.image + " erwartet " + m.getParamCount() + " Parameter, aber " + argsCount + " gegeben.");}
        }

        currentMethod.getCode().writeCall(ident.image, argsCount);
}

  final public void procedure() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {Token ident;
    jj_consume_token(VOID);
    ident = jj_consume_token(IDENT);
Method m = new Method(ident.image, false, symbolTable);
        methods.put(ident.image, m);
        currentMethod = m;
    jj_consume_token(KLAMMERAUF);
    routinenParameter();
    jj_consume_token(KLAMMERZU);
    jj_consume_token(CURLYAUF);
    routinenBlock();
    jj_consume_token(CURLYZU);
currentMethod.getCode().returnVoid();
}

  final public void function() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {Token ident;
    jj_consume_token(FUNC);
    ident = jj_consume_token(IDENT);
Method m = new Method(ident.image, true, symbolTable);
        methods.put(ident.image, m);
        currentMethod = m;
    jj_consume_token(KLAMMERAUF);
    routinenParameter();
    jj_consume_token(KLAMMERZU);
    jj_consume_token(CURLYAUF);
    routinenBlock();
    jj_consume_token(RETURN);
    expression();
    jj_consume_token(SEMICOLON);
    jj_consume_token(CURLYZU);
currentMethod.getCode().returnInt();
}

  final public void routinenParameter() throws ParseException {Token ident;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      jj_consume_token(INT);
      ident = jj_consume_token(IDENT);
currentMethod.addParameter(ident.image);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          break label_6;
        }
        jj_consume_token(COMMA);
        jj_consume_token(INT);
        ident = jj_consume_token(IDENT);
currentMethod.addParameter(ident.image);
      }
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
}

  final public void routinenBlock() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {
    constDecl();
    varDecl(true);
    statement();
}

  final public int condition() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {Token op; int jumpPlaceholder;
    expression();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQ:{
      op = jj_consume_token(EQ);
      break;
      }
    case NE:{
      op = jj_consume_token(NE);
      break;
      }
    case GE:{
      op = jj_consume_token(GE);
      break;
      }
    case GT:{
      op = jj_consume_token(GT);
      break;
      }
    case LE:{
      op = jj_consume_token(LE);
      break;
      }
    case LT:{
      op = jj_consume_token(LT);
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    expression();
switch (op.kind) {
      case EQ: jumpPlaceholder = currentMethod.getCode().if_icmpne(); break;
      case NE: jumpPlaceholder = currentMethod.getCode().if_icmpeq(); break;
      case LT: jumpPlaceholder = currentMethod.getCode().if_icmpge(); break;
      case GE: jumpPlaceholder = currentMethod.getCode().if_icmplt(); break;
      case GT: jumpPlaceholder = currentMethod.getCode().if_icmple(); break;
      case LE: jumpPlaceholder = currentMethod.getCode().if_icmpgt(); break;
      default: {if (true) throw new ParseException("wrong condition token");}
    }
    {if ("" != null) return jumpPlaceholder;}
    throw new Error("Missing return statement in function");
}

  final public void statement() throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {Token ident; int falseJump; int loopStart;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENT:{
      ident = jj_consume_token(IDENT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUAL:{
        jj_consume_token(EQUAL);
        expression();
        jj_consume_token(SEMICOLON);
int localIndex = currentMethod.getVarIndex(ident.image);
            if (localIndex != -1) {
                currentMethod.getCode().storeLocal(localIndex);
            } else if (symbolTable.isVar(ident.image)) {
                currentMethod.getCode().storeGlobal(ident.image);
            } else {
                 {if (true) throw new LWertException("Zuweisung nur an Variablen erlaubt (unbekannt): " + ident.image);}
            }
        break;
        }
      case KLAMMERAUF:{
        procCall(ident);
        jj_consume_token(SEMICOLON);
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    case PRINT:{
      jj_consume_token(PRINT);
      jj_consume_token(KLAMMERAUF);
      expression();
      jj_consume_token(KLAMMERZU);
      jj_consume_token(SEMICOLON);
currentMethod.getCode().print();
      break;
      }
    case CURLYAUF:{
      jj_consume_token(CURLYAUF);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PRINT:
        case IF:
        case WHILE:
        case CURLYAUF:
        case IDENT:{
          ;
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          break label_7;
        }
        statement();
      }
      jj_consume_token(CURLYZU);
      break;
      }
    case IF:{
      jj_consume_token(IF);
      falseJump = condition();
      statement();
      optElse(falseJump);
      break;
      }
    case WHILE:{
      jj_consume_token(WHILE);
loopStart = currentMethod.getCode().pc();
      falseJump = condition();
      statement();
int back = currentMethod.getCode().ifFalse_goto();
        currentMethod.getCode().patchJumpPlaceholder(back, loopStart);
        currentMethod.getCode().patchJumpPlaceholder(falseJump, currentMethod.getCode().pc());
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void optElse(int falseJump) throws ParseException, LWertException, UnknownSymbolException, SymbolAlreadyDefinedException, RWertException, WrongParametersException {boolean hasElse = false; int endJump = -1;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
hasElse = true;
        endJump = currentMethod.getCode().ifFalse_goto();
        currentMethod.getCode().patchJumpPlaceholder(falseJump, currentMethod.getCode().pc());
      statement();
currentMethod.getCode().patchJumpPlaceholder(endJump, currentMethod.getCode().pc());
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
if (!hasElse) {
            currentMethod.getCode().patchJumpPlaceholder(falseJump, currentMethod.getCode().pc());
        }
}

  /** Generated Token Manager. */
  public PostFixExprParseTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x1800,0x1800,0x40,0x80000,0x20,0x40000,0x80000,0x18000000,0x18000000,0x60000000,0x60000000,0x4000,0x80004000,0x80000,0x80004000,0x80000,0x80004000,0x80000,0x20,0x7e00000,0x44000,0x80010580,0x80010580,0x200,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x1,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}

  /** Constructor with InputStream. */
  public PostFixExprParse(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public PostFixExprParse(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new PostFixExprParseTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public PostFixExprParse(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new PostFixExprParseTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new PostFixExprParseTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public PostFixExprParse(PostFixExprParseTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(PostFixExprParseTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[33];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 24; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 33; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
