/* Generated By:JavaCC: Do not edit this line. PostFixExprParseConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PostFixExprParseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int FINAL = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int FUNC = 11;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int KLAMMERAUF = 14;
  /** RegularExpression Id. */
  int KLAMMERZU = 15;
  /** RegularExpression Id. */
  int CURLYAUF = 16;
  /** RegularExpression Id. */
  int CURLYZU = 17;
  /** RegularExpression Id. */
  int EQUAL = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int SEMICOLON = 20;
  /** RegularExpression Id. */
  int EQ = 21;
  /** RegularExpression Id. */
  int NE = 22;
  /** RegularExpression Id. */
  int GE = 23;
  /** RegularExpression Id. */
  int LE = 24;
  /** RegularExpression Id. */
  int GT = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int PLUS = 27;
  /** RegularExpression Id. */
  int MINUS = 28;
  /** RegularExpression Id. */
  int MULT = 29;
  /** RegularExpression Id. */
  int DIV = 30;
  /** RegularExpression Id. */
  int IDENT = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"int\"",
    "\"final\"",
    "\"print\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"func\"",
    "\"void\"",
    "\"return\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\",\"",
    "\";\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<IDENT>",
    "<NUMBER>",
  };

}
