options {
    //Hier können noch Optionen stehen z.B. static
    STATIC = false;
}

PARSER_BEGIN(PostFixExprParse) //Hier muss der Klassenname stehen
public class PostFixExprParse {
    private SymbolTable st = new SymbolTable();
    public static void main (String[] args) {
        PostFixExprParse parser = new PostFixExprParse(System.in);
        try {
            parser.program(); //Aufruf mit Startsymbol
            System.out.println("Ausdruck syntaktisch ok!");
        } catch (ParseException e) {
            System.err.println(e);
        }
    }
}
PARSER_END(PostFixExprParse)

SKIP: {
      " " //Blank
      | "\r" //Wagenrücklauf (return)
      | "\n" //Neue Zeile (new line)
      | "\t" //Tabulator
}

TOKEN: {
    < INT : "int" > //Schlüsselwort
    | < FINAL : "final" > //& später "int" einsetzen
    | < IDENT : ["a"-"z"] (["a"-"z","A"-"Z","0"-"9"])* >
    | < NUMBER : "0" | (["1"-"9"] (["0"-"9"])*) >
    | < PLUS   : "+" >
    | < MINUS  : "-" >
    | < MULT   : "*" >
    | < DIV    : "/" >
    | < KLAMMERAUF : "(" >
    | < KLAMMERZU : ")" >
    | < EQUAL : "=" >
    | < COMMA : "," >
    | < SEMICOLON : ";" >
}

void program(): {} {
    (constDecl())?
    statement()
}

void constDecl(): {} {
    <FINAL>
    <INT>
    constZuw()
    ( <COMMA> constZuw() )*
    <SEMICOLON>
}

void constZuw(): { Token ident; Token number; } {
    ident = <IDENT>
    <EQUAL>
    number = <NUMBER>
    { st.addConstant(ident.image, Integer.parseInt(number.image)); }
}

void statement():{ String s; }
{
  s = summe() <EOF>
  { System.out.println(s); }
}

String summe() : { String left, right; Token op; }
{
  left = produkt()
  (
    ( op = <PLUS>  | op = <MINUS> )
    right = produkt()
    { left = left + " " + right + " " + op.image; }
  )*
  { return left; }
}

String produkt() : { String left, right; Token op; }
{
  left = term()
  (
    ( op = <MULT> | op = <DIV> )
    right = term()
    { left = left + " " + right + " " + op.image; }
  )*
  { return left; }
}

String term() : { Token n, ident; String inside; }
{
    n = <NUMBER> { return n.image; }
    | ident = <IDENT> { return st.getSymbol(ident.image).toString(); }
    | <KLAMMERAUF> inside = summe() <KLAMMERZU> { return inside; }
}
