options {
    //Hier können noch Optionen stehen z.B. static
    STATIC = false;
}

PARSER_BEGIN(PostFixExprParse) //Hier muss der Klassenname stehen
public class PostFixExprParse {
    public static void main (String[] args) {
        PostFixExprParse parser = new PostFixExprParse(System.in);
        try {
            parser.program(); //Aufruf mit Startsymbol
            System.out.println("Ausdruck syntaktisch ok!");
        } catch (ParseException e) {
            System.err.println(e);
        }
    }
}
PARSER_END(PostFixExprParse)

SKIP: {
      " " //Blank
      | "\r" //Wagenrücklauf (return)
      | "\n" //Neue Zeile (new line)
      | "\t" //Tabulator
}

TOKEN: {
    < INT : "int" > //Schlüsselwort
    | < FINAL : "final" > //& später "int" einsetzen
    | < PRINT : "print" > // VOR IDENT!
    | < IF : "if" > // VOR IDENT!
    | < ELSE : "else" > // VOR IDENT!
    | < WHILE : "while" > // VOR IDENT!
    | < IDENT : ["a"-"z"] (["a"-"z","A"-"Z","0"-"9"])* >
    | < NUMBER : "0" | (["1"-"9"] (["0"-"9"])*) >
    | < PLUS   : "+" >
    | < MINUS  : "-" >
    | < MULT   : "*" >
    | < DIV    : "/" >
    | < KLAMMERAUF : "(" >
    | < KLAMMERZU : ")" >
    | < CURLYAUF : "{" >
    | < CURLYZU : "}" >
    | < EQUAL : "=" >
    | < COMMA : "," >
    | < SEMICOLON : ";" >
    | < COMPOP : "=" | ">" | ">=" | "<" | "<=" >
}

void program(): {} {
    constDecl()
    varDecl()
    statement()
}

void constDecl(): {} {
    ( <FINAL> <INT> constZuw() constList() <SEMICOLON> )?
}

void constZuw(): {} {
    <IDENT> <EQUAL> <NUMBER>
}

void constList(): {} {
    ( <COMMA> constZuw() constList() )?
}

void varDecl(): {} {
    ( <INT> <IDENT> varZuw() varList() <SEMICOLON> )?
}

void varZuw(): {} {
    ( <EQUAL> <NUMBER> )?
}

void varList(): {} {
    ( <COMMA> <IDENT> varZuw() varList() )?
}

void expression(): {} {
    term() summe()
}

void summe(): {} {
    (
    ( <PLUS> term() summe() )
    | ( <MINUS> term() summe())
    )?
}

void term(): {} {
    faktor() product()
}

void product(): {} {
    (
    ( <MULT> term() summe() )
    | ( <DIV> term() summe())
    )?
}

void faktor(): {} {
    <NUMBER>
    | <IDENT>
    | <KLAMMERAUF> expression() <KLAMMERZU>
}

void condition(): {} {
    expression() <COMPOP> expression()
}

void statement(): {} {
    (<IDENT> <EQUAL> expression() <SEMICOLON>)
    | ( <PRINT> <KLAMMERAUF> expression() <KLAMMERZU> <SEMICOLON> )
    | ( <CURLYAUF> stmtLIST() <CURLYZU> )
    | ( <IF> condition() statement() optElse() )
    | ( <WHILE> condition() statement() )
}

void optElse(): {} {
    ( <ELSE> statement() )?
}

void stmtLIST(): {} {
    (statement() stmtLIST())?
}